elasticsearch.url: localhost:9200
market.upload.path: C:\\Users\rlaeh\OauthLogin\src\main\resources\static\images\review
logging:
  level:
    root: info
    com.psc.sample: debug
server:
  port: 80
spring:
#spring.batch.initialize-schema: always

#  devtools:
#    livereload:
#      enabled: true
#  freemarker:
#    cache: false
#  thymeleaf:
#    cache: false
  servlet:
    multipart:
      enabled: true # 파일 업로드 가능 여부를 선택
      location: C:\\Users\rlaeh\OauthLogin\src\main\resources\static\images\review # 파일 업로드 위치
      max-request-size: 30MB # 한 번에 최대 업로드 가능 용량
      max-file-size: 10MB # 파일 하나의 최대 크기
  batch:
    initialize-schema: always # spring_batch 를 위한 테이블 자동생성
    job:
      enabled: false # CommandLineRunner 설정 해제
  application:
    name: oauth2
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        format_sql : true
  datasource:
    driver-class-name : org.mariadb.jdbc.Driver
    url: jdbc:mariadb://211.226.209.40:3306/mega?serverTimezone=Asia/Seoul&characterEncoding=utf-8
    username: dong
    password: pianist88!!
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 174612917187-c79sq0dgoh4qnl4vkdm37a8h97tftdu8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: 36bJcACbobjXzi7kGTxb
            client-secret: x0lU_wbI1j
            redirect-uri: http://localhost/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: naver
          kakao:
            clientId: 8a508edf449a39d0fcb2078d37966226
            clientSecret: YOkEQVCGOEDMgFGCPVi6JlLyua2E2JHm
            clientAuthenticationMethod: POST
            authorizationGrantType: authorization_code
            redirectUri: http://localhost/login/oauth2/code/kakao
            scope:
              - profile_image
              - account_email
              - profile_nickname
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
