logging:
  level:
    root: info
    com.psc.sample: debug
server:
  port: 80
spring:
  application:
    name: oauth2
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/aouth?ServerTimezone=Asia/Seoul
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 174612917187-c79sq0dgoh4qnl4vkdm37a8h97tftdu8.apps.googleusercontent.com
            client-secret: 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
            scope: email
          naver:
            client-id: 36bJcACbobjXzi7kGTxb
            client-secret: x0lU_wbI1j
            redirect-uri: http://localhost/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email
            client-name: naver
          kakao:
            clientId: 8a508edf449a39d0fcb2078d37966226
            clientSecret: YOkEQVCGOEDMgFGCPVi6JlLyua2E2JHm
            clientAuthenticationMethod: POST
            authorizationGrantType: authorization_code
            redirectUri: http://localhost/login/oauth2/code/kakao
            scope:
              - profile_image
              - account_email
              - profile_nickname
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id